# Generated by Django 5.1.6 on 2025-03-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigiSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('background_color', models.CharField(max_length=7)),
                ('text_color', models.CharField(max_length=7)),
            ],
        ),
    ]
