# Generated by Django 5.1.6 on 2025-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digislider',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile')], default='device_type', max_length=10),
            preserve_default=False,
        ),
    ]
