# Generated by Django 5.1.6 on 2025-03-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_slider', '0002_digislider_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digislider',
            name='device_type',
            field=models.CharField(blank=True, choices=[('TV', 'TV'), ('desktop', 'Desktop'), ('tablet', 'Tablet'), ('mobile', 'Mobile')], default='TV', max_length=10, null=True),
        ),
    ]
