# Generated by Django 5.1.6 on 2025-03-03 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_slider', '0003_alter_digislider_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='digislider',
            name='device_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='digi_slider.deviceinfo'),
        ),
    ]
